# Generated by Django 3.0 on 2021-07-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210727_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_salary',
            field=models.CharField(default=False, max_length=30, verbose_name='Amount(₦)'),
        ),
    ]
