# Generated by Django 3.0 on 2021-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210730_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_salary',
            field=models.CharField(default=False, max_length=30, verbose_name='Amount(₦)'),
        ),
    ]
