# Generated by Django 3.0 on 2021-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210730_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_salary',
            field=models.FloatField(blank=True, default=0.0, max_length=30, null=True, verbose_name='Rate Per Task (₦)'),
        ),
    ]
