# Generated by Django 3.0 on 2021-07-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210730_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='Address', max_length=150, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=20, verbose_name='Phone Number'),
        ),
    ]
