# Generated by Django 3.0 on 2021-07-30 10:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_auto_20210729_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='emp_salary',
            field=models.CharField(default=False, max_length=30, verbose_name='Amount(₦)'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='bookmarkjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.Job', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Task Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='jobapp.Category', verbose_name='Task Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Business Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=300, verbose_name='Business Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=1, verbose_name='Task type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=30, verbose_name='Amount(NGN)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Task Title'),
        ),
    ]
