# Generated by Django 3.0 on 2021-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_auto_20210730_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='emp_salary',
            field=models.CharField(blank=True, default=False, max_length=30, null=True, verbose_name='Amount(₦)'),
        ),
    ]
