# Generated by Django 3.0 on 2021-07-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_auto_20210730_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='emp_salary',
        ),
    ]
