# Generated by Django 3.0 on 2021-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_remove_job_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('1', 'Expert'), ('2', 'Intermediate'), ('3', 'Beginner')], max_length=1, verbose_name='Task type'),
        ),
    ]
