# Generated by Django 3.0 on 2021-07-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_auto_20210730_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('1', 'Expert'), ('2', 'Intermediate'), ('3', 'Beginner')], max_length=1, verbose_name='Skill Level'),
        ),
    ]
