# Generated by Django 3.0 on 2021-07-31 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_job_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
    ]
