# Generated by Django 3.0 on 2021-07-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_remove_job_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskOwner',
        ),
    ]
