# Generated by Django 3.0 on 2021-08-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_auto_20210801_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
    ]
